#! /bin/sh

sxhkd -m 1&

#
# bspwm configuration
#

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1

bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config merge_overlapping_monitors false

#
# General tweaks
#

## Setting laptop screen as primary
xrandr --output eDP-1 --primary

## Wallpaper setting (10# if for octal compatibily with bash and sh)
WALLPAPER_DIR="$HOME/Images/Wallpapers"
if [[ $((10#$(date +"%d") % 2)) -eq 0 ]] ; then
	feh --bg-fill "$WALLPAPER_DIR/mountains.jpg"
else 
	feh --bg-fill "$WALLPAPER_DIR/moondog.jpg" 
fi

## Keyboard delay & rate settings
xset r rate 190 35

#
# Hardware configuration
#

xinput --set-prop 'DLL07BE:01 06CB:7A13 Touchpad' 'libinput Tapping Enabled' 1

#xinput --set-prop "MX Master Mouse" 324 0.3

#
# Applications starting
#

# Daemons
#emacs --daemon &
#kdeconnect-indicator &
mpd &
dunst &

# Regular applets and applications
#picom &
blueman-applet &
dropbox &
#killall -q redshift-gtk || redshift-gtk &
killall -q xflux && xflux -l 45.789 -g 3.144 &

#
# Specific applications rules
#

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a Claws-mail desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a emacs state=tiled
bspc rule -a Galculator state=floating 
bspc rule -a Gnome-pomodoro state=floating

#
# Polybar
#

$HOME/.config/polybar/launch.sh
